# Generated by Django 5.2.5 on 2025-08-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='exercise_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
