# Generated by Django 5.2.5 on 2025-08-09 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tutorial_exercise_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='tutorial_videos/')),
                ('exercise_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_score', models.FloatField(help_text='Percentage accuracy of movements')),
                ('calories_burned', models.FloatField(help_text='Estimated kcal burned')),
                ('workout_duration', models.FloatField(help_text='Duration in minutes')),
                ('repetition_count', models.IntegerField(help_text='Number of detected reps')),
                ('form_consistency', models.FloatField(help_text='Consistency percentage across workout')),
                ('range_of_motion', models.FloatField(help_text='Average movement range percentage')),
                ('uploaded_video', models.FileField(upload_to='user_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
