# Generated by Django 5.2.5 on 2025-08-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_session_usersessionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersessionresult',
            name='calories_burned',
        ),
        migrations.RemoveField(
            model_name='usersessionresult',
            name='form_consistency',
        ),
        migrations.RemoveField(
            model_name='usersessionresult',
            name='range_of_motion',
        ),
        migrations.RemoveField(
            model_name='usersessionresult',
            name='repetition_count',
        ),
        migrations.RemoveField(
            model_name='usersessionresult',
            name='workout_duration',
        ),
        migrations.AlterField(
            model_name='usersessionresult',
            name='uploaded_video',
            field=models.FileField(upload_to='tutorial_videos/'),
        ),
    ]
