# Generated by Django 5.2.5 on 2025-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usersessionresult_calories_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersessionresult',
            name='calories_burned',
            field=models.FloatField(blank=True, help_text='calories burned of the user', null=True),
        ),
        migrations.AddField(
            model_name='usersessionresult',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration of exercises in minutes', null=True),
        ),
    ]
