# Generated by Django 5.2.5 on 2025-08-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usersessionresult_calories_burned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersessionresult',
            old_name='calories_burned',
            new_name='calories',
        ),
    ]
