# Generated by Django 5.2.5 on 2025-08-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='accuracy_score',
            field=models.FloatField(blank=True, default=0, help_text='Percentage accuracy of movements', null=True),
        ),
    ]
